package com.andreas.heimann.sudoku.items;

public enum RuleType {

	EXCLUDE_ENTRIES, UNIQUE_ENTRY, UNIQUE_ROW_COLUMN, ENTRY_COMBINATION, X_WING, SWORDFISH, JELLYFISH, REMOTE_PAIRS, UNIQUE_RECTANGLE

}
