package com.andreas.heimann.sudoku.items;

public enum StepType {

	ENTRY, EXCLUDE_ROW, EXCLUDE_COLUMN, EXCLUDE_SEGMENT, UNIQUE_ROW, UNIQUE_COLUMN, UNIQUE_SEGMENT, UNIQUE_SEGMENTROW, UNIQUE_SEGMENTCOLUMN, ENTRYCOMBINATION_ROW, ENTRYCOMBINATION_COLUMN, ENTRYCOMBINATION_SEGMENT

}
